In [ ]:
import torch
import numpy as np

# Basics

Tensor should take ONLY 1 Argument

In [ ]:
my_tensor = torch.tensor([1,2,3],[4,5,6])

TypeError: ignored

In [ ]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]])
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]] ,dtype = torch.float32)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([[1,2,3],[4,5,6]] ,dtype = torch.float32, device=device)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

In [ ]:

my_tensor = torch.tensor([[1,2,3],[4,5,6]] ,dtype = torch.float32, device=device, requires_grad=True)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)

In [ ]:
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)

torch.float32
cuda:0
torch.Size([2, 3])


# Torch Initialisation

In [ ]:
x = torch.empty(size = (3,3))
x

tensor([[-1.3166e+29,  3.0922e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  0.0000e+00],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22]])

In [ ]:
x = torch.zeros(size = (3,3)) #OR x = torch.empty((3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
x = torch.empty((3,3))
x

tensor([[-1.4251e+36,  3.0733e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  3.0733e-41],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22]])

In [ ]:
x = torch.ones((3,3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
x = torch.rand((3,3)) #UNIFORM DISTRIBUTION
x

tensor([[0.2238, 0.8675, 0.5901],
        [0.0357, 0.8331, 0.9299],
        [0.9802, 0.5866, 0.7941]])

In [ ]:
x = torch.eye(3) # OR x = torch.eye((3,3)) # for identity matrix 
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
x = torch.arange(start = 0, end = 10, step = 1)  #for getting values in range 
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x = torch.linspace( 3,  10,  10) #start,end, steps  #linear space 
x

tensor([ 3.0000,  3.7778,  4.5556,  5.3333,  6.1111,  6.8889,  7.6667,  8.4444,
         9.2222, 10.0000])

In [ ]:
x = torch.empty(size = (1,5)).normal_( mean = 0, std = 1)
x

tensor([[-0.6455, -1.7216, -0.1668, -1.1562,  0.5247]])

In [ ]:
x = torch.empty(size = (3,3)).uniform_( 0, 1)
x

tensor([[0.5319, 0.0499, 0.6945],
        [0.7826, 0.7402, 0.2328],
        [0.1461, 0.5970, 0.7123]])

In [ ]:
x = torch.diag(torch.rand(3))  #diagonal matrix with random values 
x

tensor([[0.7990, 0.0000, 0.0000],
        [0.0000, 0.0718, 0.0000],
        [0.0000, 0.0000, 0.2725]])

# Initialize and convert Tensors to different types

In [ ]:
tensor = torch.arange(4)
tensor

tensor([0, 1, 2, 3])

In [ ]:
print(tensor.bool())

tensor([False,  True,  True,  True])


In [ ]:
print(tensor.short())  #int16

tensor([0, 1, 2, 3], dtype=torch.int16)


In [ ]:
print(tensor.long())  #

tensor([0, 1, 2, 3])


In [ ]:
print(tensor.half()) 

tensor([0., 1., 2., 3.], dtype=torch.float16)


In [ ]:
print(tensor.float())

tensor([0., 1., 2., 3.])


In [ ]:
print(tensor.double()) 

tensor([0., 1., 2., 3.], dtype=torch.float64)


# Numpy and Tensor Interconversion

In [ ]:
np_array = np.zeros((5,5))
tensor = torch.from_numpy(np_array)
tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [ ]:
np_array_back = tensor.numpy()
np_array_back

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Mathematics

In [ ]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])
add = x + y
sub = x - y
div = torch.true_divide(x,y)  #different 
div

tensor([0.1111, 0.2500, 0.4286])

In [ ]:
t = torch.zeros(3)
t.add_(x)   #inplace 
t += x #INPLACE ADDITION
t = t + x # NORMAL ADDITION

In [ ]:
z = x.pow(2) # OR x**2
z

tensor([1, 4, 9])

In [ ]:
#MATRIX MULTIPLICATION
a = torch.tensor([ 1, 2, 3])
b = torch.tensor([ 10, 10, 10 ])
x = a.matmul(b) # tensor.dot(a,b) same results
x

tensor(60)

In [ ]:
x = a * b
x

tensor([10, 20, 30])

In [ ]:
a1 = torch.tensor(( [[ 1, 2, 3], [4,5,6]] ))
b1 = torch.tensor(( [[ 10, 10, 10 ], [10, 10, 10], [10,10,10]] ))
x = a1.matmul(b1)
x

tensor([[ 60,  60,  60],
        [150, 150, 150]])

In [ ]:
z = torch.dot(a,b)
z

tensor(60)

In [ ]:
#BATCH MATRIX MULTIPLICATION------
batch = 32
n = 10
m = 20
p = 30

tensor1 =  torch.rand((batch, n , m))
tensor2 =  torch.rand((batch, m , p))
out_bmm = torch.bmm(tensor1, tensor2) #(batch, n, p) 
out_bmm

tensor([[[5.2841, 6.4974, 4.7005,  ..., 4.2334, 5.7367, 4.4322],
         [6.0167, 6.5573, 5.1242,  ..., 5.1060, 5.2405, 5.7768],
         [5.3876, 5.3354, 4.0794,  ..., 4.0910, 4.9872, 4.8537],
         ...,
         [4.5558, 5.3013, 3.9398,  ..., 3.8358, 4.1816, 4.6959],
         [4.0113, 4.0261, 3.5180,  ..., 3.4759, 3.9081, 3.5603],
         [4.4290, 5.0949, 3.3845,  ..., 3.1234, 4.2113, 3.5151]],

        [[4.2062, 2.4739, 3.5710,  ..., 5.3325, 3.1521, 3.2161],
         [4.2566, 3.8457, 4.2890,  ..., 5.9183, 3.7412, 3.7897],
         [5.4416, 4.1152, 5.0163,  ..., 6.3379, 4.6416, 4.2462],
         ...,
         [3.8184, 3.3203, 3.4310,  ..., 4.7826, 3.0118, 3.6018],
         [4.9088, 3.9412, 4.3786,  ..., 5.9685, 4.0312, 3.6722],
         [5.0284, 3.4006, 4.0117,  ..., 5.3349, 3.5502, 3.3198]],

        [[5.5815, 5.6049, 5.5017,  ..., 5.3913, 4.2794, 5.0458],
         [6.2882, 5.7974, 6.5759,  ..., 5.0175, 3.6790, 4.9477],
         [5.7886, 6.3917, 5.9274,  ..., 5.1948, 4.2176, 5.

In [ ]:
out_bmm.shape


torch.Size([32, 10, 30])

In [ ]:
tene=torch.rand((3,4,5))  #batch(no of pages), rows, columns
tene

tensor([[[0.4956, 0.7167, 0.8379, 0.2499, 0.9660],
         [0.3265, 0.1116, 0.0483, 0.8226, 0.8581],
         [0.3472, 0.6151, 0.7838, 0.5548, 0.8751],
         [0.0680, 0.7195, 0.1165, 0.4998, 0.3121]],

        [[0.1965, 0.7468, 0.2388, 0.6612, 0.5893],
         [0.0474, 0.6252, 0.7942, 0.8827, 0.4496],
         [0.5020, 0.8408, 0.0775, 0.0331, 0.4681],
         [0.0778, 0.1427, 0.5789, 0.1942, 0.5714]],

        [[0.9399, 0.6320, 0.9744, 0.5162, 0.0059],
         [0.2915, 0.2806, 0.0504, 0.9693, 0.5284],
         [0.8870, 0.7607, 0.6468, 0.3001, 0.3339],
         [0.7388, 0.4952, 0.4216, 0.8390, 0.0459]]])

In [ ]:
a1 = torch.tensor(( [[ 1, 2, 3], [4,5,6], [7,8,9]] ))
print(a1)
sum = torch.sum(a1,dim=0) #vertically top-bottom
print(sum)
sum = torch.sum(a1,dim=1) #horizontally left-right
print(sum)
#sum = torch.sum(a2,dim=2)
#print(sum)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([12, 15, 18])
tensor([ 6, 15, 24])


In [ ]:
a1 = torch.tensor(( [[[ 1, 2, 3], [4,5,6], [7,8,9]],[[ 10, 20, 30], [40,50,60], [70,80,90]] ]))
print(a1)
sum = torch.sum(a1,dim=0) # 3rd dimension wise 
print('\n',sum)
sum = torch.sum(a1,dim=1) #vertically top-bottom
print('\n',sum)
sum = torch.sum(a1,dim=2) #horizontally left-right
print('\n',sum)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 20, 30],
         [40, 50, 60],
         [70, 80, 90]]])

 tensor([[11, 22, 33],
        [44, 55, 66],
        [77, 88, 99]])

 tensor([[ 12,  15,  18],
        [120, 150, 180]])

 tensor([[  6,  15,  24],
        [ 60, 150, 240]])


In [ ]:
#MAX
values, indices = torch.max(a1, dim=0)
print(values, indices)

tensor([7, 8, 9]) tensor([2, 2, 2])


In [ ]:
mean = torch.mean(a1,dim = 0) #a1 should be float
mean

RuntimeError: ignored

In [ ]:
mean = torch.mean(a1.float(),dim = 0)
mean

tensor([4., 5., 6.])

In [ ]:
sorted_a1, indices = torch.sort(a1, descending=True)
print(a1,'\n', sorted_a1,'\n', indices)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) 
 tensor([[3, 2, 1],
        [6, 5, 4],
        [9, 8, 7]]) 
 tensor([[2, 1, 0],
        [2, 1, 0],
        [2, 1, 0]])


In [ ]:
z = torch.clamp(a1, min = 3, max = 8) # min value - below that all min , max - all above max set to max
z

tensor([[[3, 3, 3],
         [4, 5, 6],
         [7, 8, 8]],

        [[3, 3, 3],
         [4, 5, 6],
         [7, 8, 8]]])

#Batch Indexing

In [ ]:
batch_size = 10
features = 25
x = torch.rand(batch_size, features)
x

tensor([[0.1233, 0.7616, 0.2860, 0.3810, 0.2315, 0.0934, 0.0859, 0.0848, 0.5353,
         0.5407, 0.7639, 0.3725, 0.8877, 0.7014, 0.2788, 0.4184, 0.9879, 0.5155,
         0.6070, 0.5926, 0.6255, 0.0871, 0.5081, 0.0912, 0.0087],
        [0.6630, 0.0073, 0.6622, 0.3281, 0.2814, 0.0640, 0.7587, 0.2742, 0.7908,
         0.5693, 0.5132, 0.0506, 0.5501, 0.5096, 0.8167, 0.6739, 0.0034, 0.5665,
         0.2167, 0.9020, 0.4173, 0.0255, 0.7566, 0.1186, 0.5642],
        [0.9391, 0.2618, 0.8121, 0.7745, 0.1985, 0.9600, 0.5855, 0.2491, 0.0096,
         0.1526, 0.2860, 0.6275, 0.8537, 0.4389, 0.5719, 0.7720, 0.9964, 0.0383,
         0.7094, 0.0945, 0.7530, 0.9171, 0.0718, 0.8014, 0.0109],
        [0.2761, 0.7304, 0.3388, 0.0443, 0.0391, 0.8253, 0.8288, 0.7623, 0.8417,
         0.6676, 0.6609, 0.5478, 0.4323, 0.9565, 0.6630, 0.6117, 0.7722, 0.3480,
         0.7256, 0.2970, 0.1895, 0.9253, 0.5987, 0.7206, 0.4352],
        [0.0216, 0.3211, 0.5846, 0.3701, 0.4889, 0.4918, 0.3811, 0.3921, 0.9409,
       

In [ ]:
x = torch.arange(10,20)
print(x)
print(x[(x<12) | (x > 18)])

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
tensor([10, 11, 19])


In [ ]:
x[[2,4,6]]   #for having multiple values, giving multiple indices as list of list

tensor([12, 14, 16])

In [ ]:
x

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
x[[2]]  

tensor([12])

In [ ]:
x[2]  #will fetch only one scalar value 

tensor(12)

In [ ]:
x[x.remainder(2)==0]

tensor([10, 12, 14, 16, 18])

In [ ]:
torch.where(x>12,x,x*2)    #condition, if true, if false

tensor([20, 22, 24, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
torch.tensor([1,1,2,2,2,3,3,1,1,1,1,2]).unique()

tensor([1, 2, 3])

In [ ]:
x.ndimension()

1

#Reshaping Tensor

In [ ]:
x = torch.arange(9)
xr = x.view(3,3) #work for contiguous memory
xr

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
xr = x.reshape(3,3) #works everytime but not efficient as view , but for safe option use reshape
xr

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
x1  = torch.rand(2,5)
print(x1)
x2  = torch.rand(2,5)
print(x2)
torch.cat((x1,x2), dim = 1)

tensor([[0.2207, 0.9993, 0.3529, 0.1001, 0.1405],
        [0.6020, 0.8278, 0.9696, 0.9187, 0.8104]])
tensor([[0.0092, 0.1624, 0.4763, 0.2403, 0.4159],
        [0.7968, 0.8187, 0.0274, 0.9850, 0.7813]])


tensor([[0.2207, 0.9993, 0.3529, 0.1001, 0.1405, 0.0092, 0.1624, 0.4763, 0.2403,
         0.4159],
        [0.6020, 0.8278, 0.9696, 0.9187, 0.8104, 0.7968, 0.8187, 0.0274, 0.9850,
         0.7813]])

In [ ]:
x1  = torch.arange(2)
x2  = torch.arange(2)
torch.cat((x1,x2), dim = 0)

tensor([0, 1, 0, 1])

In [ ]:
#flatten the matrix
z = x1.reshape(-1)  #2x5--> 1x10
z

tensor([0.2207, 0.9993, 0.3529, 0.1001, 0.1405, 0.6020, 0.8278, 0.9696, 0.9187,
        0.8104])

In [ ]:
z.shape

torch.Size([10])

In [ ]:
#IMPORTANT WITH BATCH
batch = 64
x = torch.rand(batch,2,5)
y = x.reshape(batch,-1) #i.e. when i dont want to touch batch
y.shape

torch.Size([64, 10])

In [ ]:
#IMPORTANT CHANGING THE AXIS
z = x.permute(0,2,1)
z.shape

torch.Size([64, 5, 2])

In [ ]:
#IMPORTANT UNSQUEEZE
x = torch.arange(10) #shape -> [10]
print(x)
print('\n',x.shape)

z=x.unsqueeze(0)
print('\n',x.unsqueeze(0).shape) #at 0th index
print('\n',z) 

y=x.unsqueeze(1)
print('\n',x.unsqueeze(1).shape) #at 1th index
print(y)

z = x.unsqueeze(0).unsqueeze(1)
print(z)
print('\n',x.unsqueeze(0).unsqueeze(1).shape) #at 0th and 1th index

#Now we dont want 1th index
z = z.squeeze(1)
print(z.shape)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

 torch.Size([10])

 torch.Size([1, 10])

 tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

 torch.Size([10, 1])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

 torch.Size([1, 1, 10])
torch.Size([1, 10])
